export const portfolioItem = [
  {
    id: 1,
    title: "GoverningDocs – Real Estate Document Analysis",
    desc: "This platform is created by following the modern and minimal design, which ensures smoothed and interactive experience for users. With Responsive Design it works perfectly on both mobile and desktop devices.",
    stack: ["React.js", "Tailwind CSS", "JavaScript"],
    photo: "/item1.png",
    liveLink: "https://governingdocs.vercel.app/",
    gitLink: "https://github.com/bddeveloperabdullah/governing",
  },
  {
    id: 2,
    title: "Wizia - AI SDRs (aiDRs) Landing Page",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam, et quisquam impedit cum maxime eius culpa, exercitationem incidunt vitae laborum cumque dolores. Quisquam fugiat id ratione explicabo porro autem, aspernatur, veritatis maiores accusantium magnam ipsam consectetur culpa corporis corrupti voluptate veniam. Non, et ab. Quia labore iusto quo aperiam culpa.",
    stack: ["React.js", "Tailwind CSS", "Framer Motion"],
    photo: "/item2.png",
    liveLink: "https://wizia-one.vercel.app/",
    gitLink: "https://github.com/bddeveloperabdullah/wizia",
  },
  {
    id: 3,
    title: "Front End Development",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam, et quisquam impedit cum maxime eius culpa, exercitationem incidunt vitae laborum cumque dolores. Quisquam fugiat id ratione explicabo porro autem, aspernatur, veritatis maiores accusantium magnam ipsam consectetur culpa corporis corrupti voluptate veniam. Non, et ab. Quia labore iusto quo aperiam culpa.",
    stack: ["React js", "Javascript", "React Bootstrap", "Swiper js"],
    photo: "/portfolio3.jpg",
  },
  {
    id: 4,
    title: "WP Development",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam, et quisquam impedit cum maxime eius culpa, exercitationem incidunt vitae laborum cumque dolores. Quisquam fugiat id ratione explicabo porro autem, aspernatur, veritatis maiores accusantium magnam ipsam consectetur culpa corporis corrupti voluptate veniam. Non, et ab. Quia labore iusto quo aperiam culpa.",
    stack: ["Wordpress", "Elementor", "Contact Form 7", "Bcrypt"],
    photo: "/portfolio4.jpg",
  },
  {
    id: 5,
    title: "Full Stack Development",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam, et quisquam impedit cum maxime eius culpa, exercitationem incidunt vitae laborum cumque dolores. Quisquam fugiat id ratione explicabo porro autem, aspernatur, veritatis maiores accusantium magnam ipsam consectetur culpa corporis corrupti voluptate veniam. Non, et ab. Quia labore iusto quo aperiam culpa.",
    stack: ["Next js", "TypeScript", "Json Server"],
    photo: "/portfolio5.jpg",
  },
];
